name: CI/CD

on:
  push:
    branches: [  master ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      
        
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" &gt; private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key user@your_vm_ip &lt;&lt; 'EOF'
            cd /path/to/app
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            git pull origin master
            sudo docker build -t myapp .
            sudo docker run -d -p 3000:3000 --name myapp myapp
          EOF
